name: CI (Linux)

on: [push, pull_request]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: check build (async)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests

      - name: tests (async)
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --all --no-fail-fast -- --nocapture

      - name: check build (blocking)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=blocking --all --bins --examples --tests

      - name: tests (blocking)
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --features=blocking --all --no-fail-fast -- --nocapture

      - name: check build (surf)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=async_surf --all --bins --examples --tests

      - name: tests (surf)
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --features=async_surf --all --no-fail-fast -- --nocapture

      - name: check build (async reqwest)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=async_reqwest --all --bins --examples --tests

      - name: tests (async reqwest)
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --features=async_reqwest --all --no-fail-fast -- --nocapture

      - name: check build (blocking reqwest)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=async_reqwest --all --bins --examples --tests

      - name: tests (blocking reqwest)
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --features=async_reqwest --all --no-fail-fast -- --nocapture

      - name: check build (async reqwest rustls)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=async_reqwest_rustls --all --bins --examples --tests

      - name: tests (async reqwest rustls)
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --features=async_reqwest_rustls --all --no-fail-fast -- --nocapture

      - name: check build (blocking reqwest rustls)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=blocking_reqwest_rustls --all --bins --examples --tests

      - name: tests (blocking reqwest rustls)
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --features=blocking_reqwest_rustls --all --no-fail-fast -- --nocapture
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: doc (async)
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --all --no-deps --features=async_reqwest --features=async_surf

      - name: doc (blocking)
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --all --no-deps --features=blocking --features=blocking_reqwest

  publish:
    name: Publish Package
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login
        env:
          SUPER_SECRET: ${{ secrets.CARGO_TOKEN }}
        run: cargo login "$SUPER_SECRET"
        shell: bash

      - name: publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
